name: docker-build

on:
  push:
    branches: ['main', 'develop']

env:
  DOCKER_IMAGE_MAIN: ghcr.io/steadfastree/ieum-api
  DOCKER_IMAGE_DEV: ghcr.io/steadfastree/ieum-api-dev
  DOCKER_CONTAINER_MAIN: ieum-api
  DOCKER_CONTAINER_DEV: ieum-api-dev

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Docker
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.IEUM_BE_ACCESS_TOKEN}}

      - name: build and push image for main
        if: github.ref == 'refs/heads/main'
        id: docker_build_main
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_IMAGE_MAIN }}:latest

      - name: build and push image for develop
        if: github.ref == 'refs/heads/develop'
        id: docker_build_dev
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_IMAGE_DEV }}:latest

  deploy_main:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ['self-hosted', 'release']
    steps:
      - name: setup .env
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST}}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT}}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD}}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME}}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE}}" >> .env
          echo "PORT=${{ secrets.PORT}}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY}}" >> .env
          echo "SECRET_KEY_ACCESS=${{ secrets.SECRET_KEY_ACCESS}}" >> .env
          echo "SECRET_KEY_REFRESH=${{ secrets.SECRET_KEY_REFRESH}}" >> .env

          cat .env
      - name: Run Docker for main
        run: |
          sudo docker stop ${{ env.DOCKER_CONTAINER_MAIN }} || true
          sudo docker rm ${{ env.DOCKER_CONTAINER_MAIN }} || true
          sudo docker rmi ${{ env.DOCKER_IMAGE_MAIN }}:latest || true
          sudo docker run --env-file ./.env --platform linux/amd64 -d --name ${{ env.DOCKER_CONTAINER_MAIN }} --network host --restart always ${{ env.DOCKER_IMAGE_MAIN }}:latest
  deploy_dev:
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ['self-hosted', 'dev']
    steps:
      - name: setup .env
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST}}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT}}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD}}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME}}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE_DEV}}" >> .env
          echo "PORT=${{ secrets.PORT}}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY}}" >> .env
          echo "SECRET_KEY_ACCESS=${{ secrets.SECRET_KEY_ACCESS}}" >> .env
          echo "SECRET_KEY_REFRESH=${{ secrets.SECRET_KEY_REFRESH}}" >> .env
          echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL}}" >> .env
          echo "RABBITMQ_URI=${{ secrets.RABBITMQ_URI}}" >> .env
          echo "KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY}}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION}}" >> .env
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME}}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID}}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}" >> .env
          echo "FIREBASE_TYPE=${{ secrets.FIREBASE_TYPE}}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID}}" >> .env
          echo "FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID}}" >> .env
          echo "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY}}" >> .env
          echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL}}" >> .env
          echo "FIREBASE_CLIENT_ID=${{ secrets.FIREBASE_CLIENT_ID}}" >> .env
          echo "FIREBASE_AUTH_URI=${{ secrets.FIREBASE_AUTH_URI}}" >> .env
          echo "FIREBASE_TOKEN_URI=${{ secrets.FIREBASE_TOKEN_URI}}" >> .env
          echo "FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL}}" >> .env
          echo "FIREBASE_CLIENT_X509_CERT_URL=${{ secrets.FIREBASE_CLIENT_X509_CERT_URL}}" >> .env
          echo "FIREBASE_UNIVERSE_DOMAIN=${{ secrets.FIREBASE_UNIVERSE_DOMAIN}}" >> .env

          cat .env
      - name: Run Docker for develop
        run: |
          sudo docker stop ${{ env.DOCKER_CONTAINER_DEV }} || true
          sudo docker rm ${{ env.DOCKER_CONTAINER_DEV }} || true
          sudo docker rmi ${{ env.DOCKER_IMAGE_DEV }}:latest || true
          sudo docker run --env-file ./.env --platform linux/amd64 -d --name ${{ env.DOCKER_CONTAINER_DEV }} --network host --restart always ${{ env.DOCKER_IMAGE_DEV }}:latest
