name: docker-build

on:
  push:
    branches: ['main', 'develop']

env:
  DOCKER_IMAGE_MAIN: ghcr.io/steadfastree/ieum-api
  DOCKER_IMAGE_DEV: ghcr.io/steadfastree/ieum-api-dev
  DOCKER_CONTAINER_MAIN: ieum-api
  DOCKER_CONTAINER_DEV: ieum-api-dev

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Docker
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.IEUM_BE_ACCESS_TOKEN}}

      - name: build and push image for main
        if: github.ref == 'refs/heads/main'
        id: docker_build_main
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_IMAGE_MAIN }}:latest

      - name: build and push image for develop
        if: github.ref == 'refs/heads/develop'
        id: docker_build_dev
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_IMAGE_DEV }}:latest

  deploy_main:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ['self-hosted', 'release']
    steps:
      - name: setup .env
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST}}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT}}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD}}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME}}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE}}" >> .env
          echo "PORT=${{ secrets.PORT}}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY}}" >> .env
          echo "SECRET_KEY_ACCESS=${{ secrets.SECRET_KEY_ACCESS}}" >> .env
          echo "SECRET_KEY_REFRESH=${{ secrets.SECRET_KEY_REFRESH}}" >> .env

          cat .env
      - name: Run Docker for main
        run: |
          sudo docker stop ${{ env.DOCKER_CONTAINER_MAIN }} || true
          sudo docker rm ${{ env.DOCKER_CONTAINER_MAIN }} || true
          sudo docker rmi ${{ env.DOCKER_IMAGE_MAIN }}:latest || true
          sudo docker run --env-file ./.env --platform linux/amd64 -d --name ${{ env.DOCKER_CONTAINER_MAIN }} --network host --restart always ${{ env.DOCKER_IMAGE_MAIN }}:latest
  deploy_dev:
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ['self-hosted', 'dev']
    steps:
      - name: setup .env
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST}}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT}}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD}}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME}}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE_DEV}}" >> .env
          echo "PORT=${{ secrets.PORT}}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY}}" >> .env
          echo "SECRET_KEY_ACCESS=${{ secrets.SECRET_KEY_ACCESS}}" >> .env
          echo "SECRET_KEY_REFRESH=${{ secrets.SECRET_KEY_REFRESH}}" >> .env

          cat .env
      - name: Run Docker for develop
        run: |
          sudo docker stop ${{ env.DOCKER_CONTAINER_DEV }} || true
          sudo docker rm ${{ env.DOCKER_CONTAINER_DEV }} || true
          sudo docker rmi ${{ env.DOCKER_IMAGE_DEV }}:latest || true
          sudo docker run --env-file ./.env --platform linux/amd64 -p 4040:${{secrets.PORT}} -d --name ${{ env.DOCKER_CONTAINER_DEV }} --restart always ${{ env.DOCKER_IMAGE_DEV }}:latest
