export enum preferredRegion {
  SEOUL = '서울',
  GYEONGGI = '경기',
  INCHEON = '인천',
  BUSAN = '부산',
  DAEGU = '대구',
  GYEONGBUK = '경북',
  ULSAN = '울산',
  GYEONGNAM = '경남',
  DAEJEON = '대전',
  CHUNGBUK = '충북',
  CHUNGNAM = '충남',
  SEJONG = '세종',
  GWANGJU = '광주',
  JEONBUK = '전북',
  JEONNAM = '전남',
  JEJU = '제주',
}

export enum preferredCompanion {
  ALONE = '나홀로',
  FAMILY = '가족',
  PARENTS = '부모님',
  KIDS = '아이',
  COUPLE = '연인',
  FRIENDS = '친구',
  PETS = '반려동물',
}

export enum MBTI {
  ISTJ = 'ISTJ',
  ISFJ = 'ISFJ',
  INFJ = 'INFJ',
  INTJ = 'INTJ',
  ISTP = 'ISTP',
  ISFP = 'ISFP',
  INFP = 'INFP',
  INTP = 'INTP',
  ESTP = 'ESTP',
  ESFP = 'ESFP',
  ENFP = 'ENFP',
  ENTP = 'ENTP',
  ESTJ = 'ESTJ',
  ESFJ = 'ESFJ',
  ENFJ = 'ENFJ',
  ENTJ = 'ENTJ',
}
